apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u8nmtrok5-python 
  janus-idp.io/tekton: u8nmtrok5-python
  backstage.io/kubernetes-id: u8nmtrok5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u8nmtrok5-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml